name: limenet-amd64
version: '16.04-0.9'
type: gadget
summary: Gadget for LimeNET amd64 devices
description: |
    This gadget enables LimeNET amd64 devices to work with Ubuntu Core
grade: stable
confinement: strict
icon: icon.png

apps:
    prepare-device:
      command: meta/hooks/prepare-device
      plugs:
        - hardware-observe
parts:
  grub:
    source: .
    plugin: make
    build-packages:
      - grub-efi-amd64-signed
      - grub-pc-bin
      - shim-signed

  hooks:
    plugin: dump
    source: hooks
    organize:
      prepare-device: meta/hooks/prepare-device
